- name: Mon playbook
  hosts: common
  become: yes
  tasks:
  - name: check connexion
    ping:

  - name: création /tmp/mamadou
    file:
      path: "/tmp/mamadou/1/2/3/4/fichier.txt"
      state: file
      owner: root
      group: root
      mode: 0755

